name: Release
on:
  push:
    branches:
      - canary
jobs:
  canary:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.org'
        # Defaults to the user or organization that owns the workflow file
        scope: '@sushiswap'
    - run: |
        npm install --save-dev @nomiclabs/hardhat-ethers@npm:hardhat-deploy-ethers ethers
        npm run build
        npm run kovan:deploy
        npm run export:all  
      env:
        MNEMONIC: ${{ secrets.TESTNET_MNEMONIC }}
        INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
        ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
        ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
    - run: |
        npm version prerelease --preid=canary
        npm publish --access public --tag canary
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    # - uses: actions/setup-node@v2
    #   with:
    #     registry-url: 'https://npm.pkg.github.com'
    # - run: npm publish --access public --tag canary
    #   env:
    #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: EndBug/add-and-commit@v7
      with:
        message: 'release: canary'
        committer_name: GitHub Actions
        committer_email: 41898282+github-actions[bot]@users.noreply.github.com