name: Release
on:
  push:
    branches:
      - canary
jobs:
  canary:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'yarn'
        cache-dependency-path: '**/yarn.lock'
    - run: yarn add --dev @nomiclabs/hardhat-ethers@npm:hardhat-deploy-ethers ethers
    - run: yarn build
    - run: |
        yarn kovan:deploy
        yarn export:all  
      env:
        MNEMONIC: ${{ secrets.TESTNET_MNEMONIC }}
        INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
        ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
        ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
    - run: npm publish --access public --tag canary
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - uses: actions/setup-node@v2
      with:
        registry-url: 'https://npm.pkg.github.com'
    - run: npm publish --access public --tag canary
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}